<div class="space-y-6 px-4 pb-8 pt-4 sm:px-5 xl:px-6" x-data="{ editorOpen: @entangle('editorOpen') }">
    <section class="relative overflow-hidden rounded-[1.7rem] border px-6 py-6 sm:px-7" style="border-color: rgba(var(--theme-border-color-rgb), 0.68); background:
        radial-gradient(circle at top left, rgba(var(--theme-accent-rgb), 0.16), transparent 32%),
        linear-gradient(135deg, color-mix(in srgb, var(--theme-surface-overlay) 94%, transparent), color-mix(in srgb, var(--theme-surface-base) 96%, transparent));">
        <div class="relative flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between">
            <div class="max-w-3xl">
                <div class="inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-[11px] font-semibold uppercase tracking-[0.24em]" style="border-color: rgba(var(--theme-accent-rgb), 0.22); background-color: rgba(var(--theme-accent-rgb), 0.08); color: var(--theme-accent);">
                    <span class="inline-flex h-2 w-2 rounded-full" style="background-color: var(--theme-accent);"></span>
                    {{ __('Caption Library') }}
                </div>
                <h1 class="mt-4 text-[2rem] font-semibold tracking-[-0.06em] sm:text-[2.4rem]" style="color: var(--theme-header-text-color);">{{ __('Captions Workspace') }}</h1>
                <p class="mt-3 max-w-2xl text-sm leading-7 sm:text-[15px]" style="color: var(--theme-muted-text-color);">
                    {{ __('Store AI and manual caption blocks in one place, filter them quickly, and keep high-performing copy ready for publishing.') }}
                </p>
            </div>

            <div class="flex flex-wrap items-center gap-3">
            <x-ui.button :href="route('portal.ai-studio')" variant="outline" wire:navigate>
                <i class="fa-light fa-sparkles"></i>
                {{ __('Open AI Studio') }}
            </x-ui.button>
            <x-ui.button type="button" wire:click="openCreateEditor">
                <i class="fa-light fa-plus"></i>
                {{ $editingId ? __('New caption') : __('Create caption') }}
            </x-ui.button>
            </div>
        </div>
    </section>

    <section class="grid gap-4 md:grid-cols-2 2xl:grid-cols-4">
        <x-ui.metric-card
            :label="__('Library items')"
            :value="$stats['total'] ?? 0"
            :description="__('Total saved captions')"
            icon="fa-light fa-books"
            accent="primary"
            class="min-h-[150px]"
        />
        <x-ui.metric-card
            :label="__('AI captions')"
            :value="$stats['ai'] ?? 0"
            :description="__('Generated by AI tools')"
            icon="fa-light fa-sparkles"
            accent="success"
            class="min-h-[150px]"
        />
        <x-ui.metric-card
            :label="__('Manual captions')"
            :value="$stats['manual'] ?? 0"
            :description="__('Written and curated manually')"
            icon="fa-light fa-pen"
            accent="neutral"
            class="min-h-[150px]"
        />
        <x-ui.metric-card
            :label="__('Active')"
            :value="$stats['active'] ?? 0"
            :description="__('Currently ready for publishing')"
            icon="fa-light fa-badge-check"
            accent="warning"
            class="min-h-[150px]"
        />
    </section>

    

    <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_26rem]">
        <section class="space-y-5">
            <x-ui.surface-card padding="lg" featured accent="primary">
                <div class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
                    <div>
                        <p class="text-sm font-semibold" style="color: var(--theme-header-text-color);">{{ __('Caption Inventory') }}</p>
                        <p class="mt-1 text-sm leading-6" style="color: var(--theme-muted-text-color);">{{ __('Browse saved captions, filter by source or status, and reopen any entry for editing.') }}</p>
                    </div>
                    <x-ui.badge variant="primary">{{ count($captions) }} {{ __('shown') }}</x-ui.badge>
                </div>

                <div class="mt-5 grid gap-3 lg:grid-cols-[minmax(0,1fr)_12rem_12rem_auto]">
                    <x-ui.input wire:model.live.debounce.300ms="search" :placeholder="__('Search name, caption, or notes')" />
                    <x-ui.select wire:model.live="sourceFilter">
                        <option value="">{{ __('All sources') }}</option>
                        <option value="manual">{{ __('Manual') }}</option>
                        <option value="ai">{{ __('AI') }}</option>
                    </x-ui.select>
                    <x-ui.select wire:model.live="statusFilter">
                        <option value="">{{ __('All statuses') }}</option>
                        <option value="active">{{ __('Active') }}</option>
                        <option value="draft">{{ __('Draft') }}</option>
                        <option value="archived">{{ __('Archived') }}</option>
                    </x-ui.select>
                    <div class="flex items-center gap-3">
                        <x-ui.button type="button" variant="ghost" wire:click="resetFilters">
                            {{ __('Reset') }}
                        </x-ui.button>
                    </div>
                </div>
            </x-ui.surface-card>

            @if ($captions->isNotEmpty())
                <div class="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">
                    @foreach ($captions as $caption)
                        @php
                            $sourceVariant = $caption->source_type === 'ai' ? 'primary' : 'neutral';
                            $statusVariant = match ($caption->status) {
                                'active' => 'success',
                                'draft' => 'neutral',
                                default => 'danger',
                            };
                        @endphp
                        <x-ui.surface-card padding="md" class="h-full">
                            <div class="flex h-full flex-col">
                                <div class="flex items-start justify-between gap-3">
                                    <div class="flex flex-wrap items-center gap-2">
                                        <x-ui.badge :variant="$sourceVariant">{{ strtoupper($caption->source_type) }}</x-ui.badge>
                                        <x-ui.badge :variant="$statusVariant">{{ strtoupper($caption->status) }}</x-ui.badge>
                                    </div>
                                    <span class="text-xs font-medium" style="color: var(--theme-muted-text-color);">{{ $caption->updated_at?->diffForHumans() }}</span>
                                </div>

                                <div class="mt-4">
                                    <p class="text-base font-semibold" style="color: var(--theme-header-text-color);">{{ $caption->name }}</p>
                                    <p class="mt-3 text-sm leading-7" style="color: var(--theme-header-text-color);">{{ \Illuminate\Support\Str::limit($caption->content, 220) }}</p>
                                </div>

                                @php
                                    $visibleTags = collect($caption->tags ?? [])
                                        ->map(fn ($tag) => trim((string) $tag))
                                        ->filter()
                                        ->reject(fn ($tag) => in_array(Str::lower($tag), ['manual', 'ai', 'misc', 'placeholder', 'short-text', 'short-content'], true))
                                        ->take(2)
                                        ->values();
                                @endphp

                                @if ($visibleTags->isNotEmpty())
                                    <div class="mt-4 flex flex-wrap gap-2">
                                        @foreach ($visibleTags as $tag)
                                            <x-ui.badge variant="neutral">{{ $tag }}</x-ui.badge>
                                        @endforeach
                                    </div>
                                @endif

                                @if (! empty($caption->notes))
                                    <p class="mt-4 text-sm leading-6" style="color: var(--theme-muted-text-color);">{{ \Illuminate\Support\Str::limit($caption->notes, 120) }}</p>
                                @endif

                                <div class="mt-5 flex items-center gap-2 pt-2" x-data="{ confirmDeleteOpen: false }">
                                    <x-ui.button type="button" size="sm" variant="outline" wire:click="editCaption({{ $caption->id }})">{{ __('Edit') }}</x-ui.button>
                                    <x-ui.button type="button" size="sm" variant="danger" x-on:click="confirmDeleteOpen = true">{{ __('Delete') }}</x-ui.button>

                                    <template x-teleport="body">
                                        <div
                                            x-cloak
                                            x-show="confirmDeleteOpen"
                                            class="fixed inset-0 z-[120] flex items-center justify-center p-6"
                                            x-on:keydown.escape.window="confirmDeleteOpen = false"
                                        >
                                            <div class="absolute inset-0 bg-white/55 backdrop-blur-[6px] dark:bg-slate-950/55" x-on:click="confirmDeleteOpen = false"></div>

                                            <div x-show="confirmDeleteOpen" x-transition.opacity.scale.90 class="relative w-full max-w-[26rem]">
                                                <div class="overflow-hidden rounded-[1.15rem] border shadow-[0_32px_80px_-34px_rgba(15,23,42,0.32)]" style="border-color: color-mix(in srgb, var(--theme-border-color) 58%, transparent); background-color: var(--theme-surface-overlay);">
                                                    <div class="flex items-start justify-between gap-4 border-b px-5 py-4 sm:px-6 sm:py-5" style="border-color: color-mix(in srgb, var(--theme-border-color) 52%, transparent);">
                                                        <div class="min-w-0">
                                                            <h3 class="text-[1.05rem] font-semibold tracking-[-0.02em]" style="color: var(--theme-header-text-color);">{{ __('Delete caption?') }}</h3>
                                                            <p class="mt-2 text-[15px] leading-7" style="color: var(--theme-muted-text-color);">{{ __('This will permanently remove ":name" from your caption library.', ['name' => $caption->name]) }}</p>
                                                        </div>

                                                        <button type="button" style="color: var(--theme-muted-text-color);" x-on:click="confirmDeleteOpen = false">
                                                            <i class="fa-light fa-xmark text-lg"></i>
                                                        </button>
                                                    </div>

                                                    <div class="px-5 py-4 sm:px-6 sm:py-5">
                                                        <p class="text-sm leading-7" style="color: var(--theme-muted-text-color);">
                                                            {{ __('You can keep editing or cancel now if this caption might still be reused later.') }}
                                                        </p>
                                                    </div>

                                                    <div class="border-t bg-slate-50/70 px-5 py-4 sm:px-6" style="border-color: color-mix(in srgb, var(--theme-border-color) 52%, transparent);">
                                                        <div class="flex items-center justify-end gap-3">
                                                            <x-ui.button type="button" variant="outline" x-on:click="confirmDeleteOpen = false">
                                                                {{ __('Cancel') }}
                                                            </x-ui.button>
                                                            <x-ui.button type="button" variant="danger" wire:click="deleteCaption({{ $caption->id }})" x-on:click="confirmDeleteOpen = false">
                                                                {{ __('Delete caption') }}
                                                            </x-ui.button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </template>
                                </div>
                            </div>
                        </x-ui.surface-card>
                    @endforeach
                </div>
            @else
                <x-ui.empty
                    icon="fa-light fa-pen-field"
                    :title="__('No captions found')"
                    :description="__('Build a reusable caption library from AI-generated blocks or manual copy for faster publishing.')"
                >
                    <div class="inline-flex items-center gap-2 rounded-full border px-3 py-2 text-sm" style="border-color: rgba(var(--theme-border-color-rgb), 0.48); background-color: color-mix(in srgb, var(--theme-surface-base) 94%, transparent); color: var(--theme-muted-text-color);">
                        <span class="font-semibold" style="color: var(--theme-header-text-color);">{{ __('Start building') }}</span>
                        <span>&bull;</span>
                        <span>{{ __('Create, tag, reuse.') }}</span>
                    </div>
                </x-ui.empty>
            @endif
        </section>

        <div id="caption-editor" class="hidden xl:sticky xl:top-24 xl:self-start xl:block">
            <x-ui.surface-card padding="lg" featured :accent="$editingId ? 'warning' : 'primary'">
                @include('appcaptions::livewire.partials.editor-form')
            </x-ui.surface-card>
        </div>
    </div>

    <template x-teleport="body">
        <div
            x-cloak
            x-show="editorOpen"
            class="fixed inset-0 z-[120] flex items-end justify-center p-0 xl:hidden"
            x-on:keydown.escape.window="editorOpen = false"
        >
            <div class="absolute inset-0 bg-slate-950/45 backdrop-blur-[4px]" x-on:click="editorOpen = false"></div>

            <div x-show="editorOpen" x-transition.opacity.scale.95 class="relative w-full max-w-2xl">
                <div class="max-h-[88vh] overflow-y-auto rounded-t-[1.4rem] border px-5 py-5 shadow-[0_-24px_70px_-30px_rgba(15,23,42,0.45)]" style="border-color: color-mix(in srgb, var(--theme-border-color) 58%, transparent); background-color: var(--theme-surface-overlay);">
                    <div class="mb-4 flex items-center justify-between gap-3">
                        <div class="flex items-center gap-2">
                            <span class="inline-flex h-9 w-9 items-center justify-center rounded-2xl" style="background-color: rgba(var(--theme-accent-rgb), 0.12); color: var(--theme-accent);">
                                <i class="fa-light fa-pen-field"></i>
                            </span>
                            <p class="text-sm font-semibold" style="color: var(--theme-header-text-color);">{{ $editingId ? __('Edit caption') : __('Create caption') }}</p>
                        </div>

                        <x-ui.button type="button" variant="ghost" x-on:click="editorOpen = false">
                            <i class="fa-light fa-xmark"></i>
                        </x-ui.button>
                    </div>

                    @include('appcaptions::livewire.partials.editor-form')
                </div>
            </div>
        </div>
    </template>
</div>
