<?php

return [
    'disk' => env('APP_FILES_DISK', 'public'),
    'admin_route_prefix' => 'admin/files',
    'portal_route_prefix' => 'portal/files',
    'default_max_upload_mb' => 20,
    'enable_upload_from_url' => true,
    'enable_google_drive' => false,
    'enable_dropbox' => false,
    'enable_onedrive' => false,
    'enable_adobe_express' => false,
    'enable_quick_delete_action' => true,
    'allowed_extensions' => [
        'jpg',
        'jpeg',
        'png',
        'gif',
        'webp',
        'svg',
        'pdf',
        'doc',
        'docx',
        'xls',
        'xlsx',
        'csv',
        'txt',
        'mp4',
        'mp3',
        'wav',
        'zip',
        'json',
    ],
];
